/**
 * Hand-designed Tiny Swords island for /stad.
 *
 * 44 cols × 30 rows elevation grid. Each character:
 *   .  = water
 *   1  = sea-level grass (flat template)
 *   2  = plateau grass   (raised template + cliff wall south)
 *
 * Designed to match the look of the official Tiny Swords promo screenshot:
 * organic coastline, two raised plateaus (a castle-ish area top-left and
 * a tower area bottom-centre), natural indents and bulges, a clear band of
 * sea-level grass in the middle where buildings can sit.
 *
 * Authoring notes:
 * - Every plateau (2) cell must have ALL four cardinal neighbours be grass
 *   (1 or 2). No plateau drops directly to water — always a 1-tile sea-level
 *   ring around any plateau. Keeps the autotile corner cases clean.
 * - No 1-tile-wide peninsulas (would create N+S-both-lower cells that the
 *   9-slot autotile can't represent cleanly).
 * - Centre mass is intentionally thick so buildings have room.
 */

export const MAP_COLS = 44;
export const MAP_ROWS = 30;

// prettier-ignore
export const ELEVATION_TEXT = `
............................................
............................................
........1111................................
.......1122211...............................
......112222211..............................
......112222211..............................
.......1112211...............................
........11111................................
........11111....111111......................
........111111.11111111......................
........1111111111111111.....................
..........1111111111111111...................
...........111111111111111...................
...........11111111111111111.................
...........111111222211111111................
............11122222221111111................
............11222222221111111.................
.............112222221111111..................
..............1111111111111...................
..............1111111111111...................
...............11111111111....................
...............1111111111.....................
................1111111.......................
.................111..........................
................................................
................................................
................................................
................................................
................................................
................................................
`;

export function parseElevation(): number[][] {
  const lines = ELEVATION_TEXT.trim().split('\n');
  const rows: number[][] = [];
  for (const raw of lines) {
    const padded = raw.padEnd(MAP_COLS, '.');
    const row: number[] = [];
    for (let i = 0; i < MAP_COLS; i++) {
      const ch = padded[i];
      if (ch === '1') row.push(1);
      else if (ch === '2') row.push(2);
      else row.push(0);
    }
    rows.push(row);
  }
  // Ensure exact row count
  while (rows.length < MAP_ROWS) rows.push(new Array(MAP_COLS).fill(0));
  return rows.slice(0, MAP_ROWS);
}
